# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [30]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key
gmaps.configure(api_key= g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [5]:
cities_weather_df = pd.read_csv('Cities_weather.csv')
cities_weather_df.dropna(inplace = True)
cities_weather_df.head()

,Unnamed: 0,City,Lat,Lng,Temperature,Humidity,Cloudiness,Wind Speed,Country
0,0,codrington,-38.2667,141.9667,10.79,68.0,100.0,4.54,AU
2,2,sept-iles,50.2001,-66.3821,8.92,77.0,100.0,5.36,CA
3,3,takoradi,4.8845,-1.7554,24.77,86.0,100.0,1.60,GH
4,4,zhicheng,30.2956,111.5047,30.80,48.0,1.0,2.04,CN
5,5,kavaratti,10.5669,72.6420,27.52,80.0,100.0,8.02,IN

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [42]:
locations = cities_weather_df[["Lat", "Lng"]]
humidity = cities_weather_df["Humidity"].astype(float)

fig = gmaps.figure(zoom_level = 2, center = (53,46))

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, 
                                 dissipating = False, max_intensity = 10,
                                 point_radius = 1)


# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [43]:
cities_filtered_df = cities_weather_df[cities_weather_df['Temperature'].between(23,33)]
cities_filtered_df = cities_filtered_df[cities_filtered_df['Humidity'].between(0,30)]
cities_filtered_df = cities_filtered_df[cities_filtered_df['Cloudiness'].between(0,20)]
cities_filtered_df = cities_filtered_df[cities_filtered_df['Wind Speed'].between(0,15)]
cities_filtered_df = cities_filtered_df.drop(["Unnamed: 0"], axis = 1, inplace = False)
cities_filtered_df

,City,Lat,Lng,Temperature,Humidity,Cloudiness,Wind Speed,Country
12,pervomayskoye,43.9190,46.7102,28.95,21.0,0.0,2.65,RU
47,beyneu,45.3167,55.2000,30.07,11.0,3.0,5.28,KZ
49,adrar,20.5022,-10.0711,31.88,26.0,9.0,7.55,MR
97,ankazoabo,-22.2833,44.5167,32.44,25.0,0.0,3.00,MG
141,karoi,-16.8099,29.6925,27.03,26.0,5.0,5.27,ZW
186,alice springs,-23.7000,133.8833,32.75,12.0,1.0,2.57,AU
209,hakkari,37.5833,44.1667,23.88,16.0,0.0,2.06,TR
219,saint george,37.1041,-113.5841,23.85,21.0,1.0,1.34,US
235,kosonsoy,41.2561,71.5508,26.31,10.0,0.0,3.84,UZ
240,masvingo,-20.0637,30.8277,30.96,20.0,0.0,2.54,ZW
258,nalut,30.3333,10.8500,27.47,27.0,2.0,6.08,LY
281,nurota,40.5614,65.6886,31.05,11.0,0.0,2.79,UZ
292,tyup,42.7276,78.3648,23.43,21.0,0.0,4.40,KG
316,ampanihy,-24.7000,44.7500,32.32,24.0,0.0,1.68,MG
326,sakakah,29.9697,40.2064,32.10,22.0,0.0,2.82,SA
334,boralday,43.3578,76.8594,27.92,16.0,20.0,3.00,KZ
366,jiuquan,39.7432,98.5174,25.09,22.0,0.0,5.16,CN
434,yashkul,46.1711,45.3435,28.74,27.0,0.0,3.58,RU
437,ahar,38.4774,47.0699,26.18,24.0,0.0,2.62,IR
456,komsomolskiy,40.4272,71.7189,31.40,13.0,0.0,1.03,UZ
492,shache,38.4167,77.2406,30.56,15.0,7.0,1.92,CN
549,nampula,-15.1165,39.2666,28.97,30.0,20.0,4.63,MZ
575,changji,44.0167,87.3167,28.44,21.0,0.0,4.00,CN
603,korla,41.7597,86.1469,29.33,19.0,1.0,3.88,CN

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [44]:
cities_filtered_df['Hotel Name'] = ""
cities_filtered_df.head()

,City,Lat,Lng,Temperature,Humidity,Cloudiness,Wind Speed,Country,Hotel Name
12,pervomayskoye,43.9190,46.7102,28.95,21.0,0.0,2.65,RU,
47,beyneu,45.3167,55.2000,30.07,11.0,3.0,5.28,KZ,
49,adrar,20.5022,-10.0711,31.88,26.0,9.0,7.55,MR,
97,ankazoabo,-22.2833,44.5167,32.44,25.0,0.0,3.00,MG,
141,karoi,-16.8099,29.6925,27.03,26.0,5.0,5.27,ZW,

In [45]:
for index, row in cities_filtered_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    locations = f"{lat},{lng}"
  
    params = {
    "rankby": "distance",
    "location": locations,
    "types": "lodging",
    "key": g_key
}

    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    
    try:
        response = (requests.get(url, params = params)).json()
        cities_filtered_df.loc[index, "Hotel Name"] = response["results"][0]["name"]
        print("Found hotel " + str(response["results"][0]["name"]))
       
    except (KeyError, IndexError):
        pass

Found hotel Gostinitsa Terek
Found hotel NUR
Found hotel ENCEIN BUREAU CISCO
Found hotel Chikangwe Guest houses
Found hotel Aurora Alice Springs
Found hotel University Inn "College Inn"
Found hotel Гостиница "Goldstar'
Found hotel The Stallion Masvingo.
Found hotel Ruslan Guest house Nurata toure
Found hotel Yurtochnyy Gorodok "Ybrayym-Nur"
Found hotel Angora Hotel
Found hotel شراشف أم رجاء
Found hotel Zhetysu, Too Zhetysu
Found hotel 美美商务宾馆
Found hotel Bon Voyazh
Found hotel هتل رضوی
Found hotel Янги Маргилан
Found hotel Chuanwazi Restaurant
Found hotel Residencia Expresso
Found hotel 水利旅馆
Found hotel Ross Quest Hotel

In [46]:
cities_filtered_df = cities_filtered_df.drop([49, 209, 258]) 
cities_filtered_df

,City,Lat,Lng,Temperature,Humidity,Cloudiness,Wind Speed,Country,Hotel Name
12,pervomayskoye,43.9190,46.7102,28.95,21.0,0.0,2.65,RU,Gostinitsa Terek
47,beyneu,45.3167,55.2000,30.07,11.0,3.0,5.28,KZ,NUR
97,ankazoabo,-22.2833,44.5167,32.44,25.0,0.0,3.00,MG,ENCEIN BUREAU CISCO
141,karoi,-16.8099,29.6925,27.03,26.0,5.0,5.27,ZW,Chikangwe Guest houses
186,alice springs,-23.7000,133.8833,32.75,12.0,1.0,2.57,AU,Aurora Alice Springs
219,saint george,37.1041,-113.5841,23.85,21.0,1.0,1.34,US,"University Inn ""College Inn"""
235,kosonsoy,41.2561,71.5508,26.31,10.0,0.0,3.84,UZ,"Гостиница ""Goldstar'"
240,masvingo,-20.0637,30.8277,30.96,20.0,0.0,2.54,ZW,The Stallion Masvingo.
281,nurota,40.5614,65.6886,31.05,11.0,0.0,2.79,UZ,Ruslan Guest house Nurata toure
292,tyup,42.7276,78.3648,23.43,21.0,0.0,4.40,KG,"Yurtochnyy Gorodok ""Ybrayym-Nur"""
316,ampanihy,-24.7000,44.7500,32.32,24.0,0.0,1.68,MG,Angora Hotel
326,sakakah,29.9697,40.2064,32.10,22.0,0.0,2.82,SA,شراشف أم رجاء
334,boralday,43.3578,76.8594,27.92,16.0,20.0,3.00,KZ,"Zhetysu, Too Zhetysu"
366,jiuquan,39.7432,98.5174,25.09,22.0,0.0,5.16,CN,美美商务宾馆
434,yashkul,46.1711,45.3435,28.74,27.0,0.0,3.58,RU,Bon Voyazh
437,ahar,38.4774,47.0699,26.18,24.0,0.0,2.62,IR,هتل رضوی
456,komsomolskiy,40.4272,71.7189,31.40,13.0,0.0,1.03,UZ,Янги Маргилан
492,shache,38.4167,77.2406,30.56,15.0,7.0,1.92,CN,Chuanwazi Restaurant
549,nampula,-15.1165,39.2666,28.97,30.0,20.0,4.63,MZ,Residencia Expresso
575,changji,44.0167,87.3167,28.44,21.0,0.0,4.00,CN,水利旅馆
603,korla,41.7597,86.1469,29.33,19.0,1.0,3.88,CN,Ross Quest Hotel

In [47]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in cities_filtered_df.iterrows()]
locations = cities_filtered_df[["Lat", "Lng"]]

In [48]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,  hotel_info)
fig.add_layer(markers)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))